// CSS module type declarations
// next-env.d.ts is auto-generated by Next.js and cannot be edited — put custom declarations here instead.

declare module "*.css" {
  const content: Record<string, string>;
  export default content;
}
